### ISSUE TITLE
EISDIR Error while running ngma

### ISSUE THREAD

**Issue by ajojra** [ellamaolson/ngMigration-Assistant#22]
Error 1:  ```
{ Error: EISDIR: illegal operation on a directory, read
    at Object.fs.readSync (fs.js:675:18)
    at tryReadSync (fs.js:540:20)
    at Object.fs.readFileSync (fs.js:583:19)
    at AnalysisTool.testFile (/usr/local/lib/node_modules/ngma/bin/analysisTool.js:196:38)
    at AnalysisTool.runAnalysis (/usr/local/lib/node_modules/ngma/bin/analysisTool.js:174:18)
    at AnalysisTool.countLinesOfCode.then.sourceLines (/usr/local/lib/node_modules/ngma/bin/analysisTool.js:70:18)
    at <anonymous>
    at process._tickCallback (internal/process/next_tick.js:188:7) errno: -21, code: 'EISDIR', syscall: 'read' }
```

Output:
App Statistics
  * **Complexity: 0 controllers, 0 AngularJS components,** 55 JavaScript files, and 0 Typescript files.

**Comment by trejoramiro** [comment]
Having the same issue, has anyone found a fix?

**Comment by trejoramiro** [comment]
Found the cause. I was not targeting my app's javascript.

@Aman-Jojra make sure the folder path points to where your angular files are located.  In most cases that would be the scripts folder. e.g. `.../scripts/   ngma <folder-name-holding-angularjs> `

**Comment by ashclarke** [comment]
My issue is caused by third-party scripts being read. 

This is because:

* I want ngma to look at the `app` sub-directory, in the parent folder.
* I have other folders that are siblings of `app` that mustn't be analysed.
* I have a `third-party` folder within `app` - This is again because of the sibling folders.
* I have a `.gitignore` in the parent folder.

Example:

```
Parent Folder
|__ app
|    |__ feature
|    |__ feature
|    |__ third-party
|        |__ dependency
|            |__ erroring-file.js
|__ sibling folder
|__ .gitignore
```

It would be great to specify the ignore file, e.g.

`ngma app --ignore ..\.gitignore`

For now, I've just copied the `.gitignore` into the app directory. 😏
