### ISSUE TITLE
Error while starting ngma

### ISSUE THREAD

**Issue by mhayen** [ellamaolson/ngMigration-Assistant#6]
Hi,
After installing ngma with npm install -g ngma I tried to run it on a old angularJS project.
Unfortunately I get this error:

`/usr/local/lib/node_modules/ngma/bin/analysisTool.js:112
        allIgnoreGlobs = [...gitignore(rootpath + "/.gitignore"), ...defaultIgnoreGlobs].filter((pattern) => {
                          ^^^

SyntaxError: Unexpected token ...
    at exports.runInThisContext (vm.js:53:16)
    at Module._compile (module.js:374:25)
    at Object.Module._extensions..js (module.js:417:10)
    at Module.load (module.js:344:32)
    at Function.Module._load (module.js:301:12)
    at Module.require (module.js:354:17)
    at require (internal/module.js:12:17)
    at Object.<anonymous> (/usr/local/lib/node_modules/ngma/bin/main.js:11:24)
    at Module._compile (module.js:410:26)
    at Object.Module._extensions..js (module.js:417:10)
`

**Comment by ellamaolson** [comment]
Interesting error, I will look into this.

**Comment by liorcode** [comment]
Might want to verify your node version is > 6 (which supports ES6 array destructuring)

**Comment by pankajparkar** [comment]
@mhayen Even I have had similar error after following the command mentioned in `readme.md`

then I had used 

`npm i -g ngma@latest`

After installation of this solved my issue.
